// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzqydeahhbcpkqlpmkym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6cXlkZWFoaGJjcGtxbHBta3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTUyNzksImV4cCI6MjA2Njk3MTI3OX0.9S1Kx29lfPEKeiElHL9In1WahRQE1o0Cn3OWTz-lPLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});